service: serverless-http-api
frameworkVersion: "4"

provider:
    name: aws
    runtime: nodejs22.x
    lambdaHashingVersion: "20201221"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
    - serverless-offline
