name: Terraform Destroy

on:
  workflow_dispatch:

env:
  PREFIX: ${{ vars.PREFIX }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} 

      - name: Terraform Init
        working-directory: ./infra
        run: |
          terraform init \
          -input=false \
          -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Destroy
        working-directory: ./infra
        run: terraform apply -auto-approve -var="prefix=${{ env.PREFIX }}"
